# EC2 Keypair (FIRST - required by all EC2 instances)
module "ec2_keypair" {
  source = "./modules/ec2_keypair"

  key_name = var.key_name
  tags     = local.common_tags
}

# TLS Certificate (SECOND - for HTTPS)
module "tls_certificate" {
  source = "./modules/tls_certificate"
}

module "network" {
  source = "./modules/network"

  tags = local.common_tags
}

locals {
  ami_id   = var.ami_id != "" ? var.ami_id : data.aws_ami.ubuntu.id
  key_name = module.ec2_keypair.key_name
}

# Application Load Balancer
module "alb" {
  source = "./modules/alb"

  vpc_id                  = module.network.vpc_id
  subnets                 = module.network.public_subnets
  alb_name                = "arquisoft-alb"
  alb_port                = 80
  target_port             = 8000
  health_check_path       = "/health/"
  enable_fastapi_target   = true
  fastapi_target_port     = 8001
  fastapi_health_check_path = "/health"

  tags = local.common_tags
}

# ─────────────────────────────────────────────────────
# RDS — Created BEFORE EC2 so we have the real endpoint
# ─────────────────────────────────────────────────────
module "rds" {
  source = "./modules/rds"

  vpc_id          = module.network.vpc_id
  private_subnets = module.network.private_subnets
  allowed_sg_ids  = []
  db_password     = var.db_password

  tags = local.common_tags
}

# SQS Queue for Celery tasks
module "sqs" {
  source = "./modules/sqs"

  queue_name = "arquisoft-celery-tasks"
  tags       = local.common_tags
}

# ─────────────────────────────────────────────────────
# Dynamic .env — generated with REAL values from RDS/SQS
# ─────────────────────────────────────────────────────
locals {
  generated_env_file = <<-EOT
# Auto-generated by Terraform
DB_NAME=${module.rds.db_name}
DB_USER=${module.rds.db_username}
DB_PASSWORD=${var.db_password}
DB_HOST=${module.rds.db_address}
DB_PORT=${module.rds.db_port}

# SQS
AWS_SQS_URL=${module.sqs.queue_url}
AWS_SQS_QUEUE_NAME=${module.sqs.queue_name}
AWS_REGION=us-east-1

# CloudWatch Logs (ASR-10)
AWS_CLOUDWATCH_LOG_GROUP=/arquisoft/django
AWS_CLOUDWATCH_SECURITY_LOG_GROUP=/arquisoft/django/security
AWS_CLOUDWATCH_CELERY_LOG_GROUP=/arquisoft/celery
AWS_CLOUDWATCH_CELERY_FAILURES_LOG_GROUP=/arquisoft/celery/failures
AWS_CLOUDWATCH_RETENTION_DAYS=90
CLOUDWATCH_LOG_GROUP=/arquisoft/django/security
CLOUDWATCH_LOG_STREAM=security-audit

# SES (Email Notifications)
AWS_SES_SENDER_EMAIL=noreply@arquisoft.com
AWS_SES_RECIPIENT_EMAIL=${var.recipient_email}
AWS_SES_SUCCESS_TEMPLATE=analisis-resultado-exito
AWS_SES_FAILURE_TEMPLATE=analisis-resultado-error

# Django
DJANGO_SETTINGS_MODULE=config.django_settings
DJANGO_DEBUG=True
ALLOWED_HOSTS="*"
EOT
}

# ─────────────────────────────────────────────────────
# IAM — AWS Academy uses LabInstanceProfile (LabRole)
# Custom IAM roles/profiles cannot be created in Academy
# ─────────────────────────────────────────────────────

# ─────────────────────────────────────────────────────
# EC2 Django (uses dynamic .env with real RDS endpoint)
# ─────────────────────────────────────────────────────
module "ec2_django" {
  source = "./modules/ec2_django"

  vpc_id               = module.network.vpc_id
  public_subnets       = module.network.public_subnets
  ami_id               = local.ami_id
  key_name             = local.key_name
  github_token         = var.github_token
  env_file             = local.generated_env_file
  target_group_arn     = module.alb.target_group_arn
  alb_sg_id            = module.alb.alb_sg_id
  iam_instance_profile = "LabInstanceProfile"

  tags = local.common_tags

  depends_on = [module.rds, module.sqs]
}

# Allow Django SG to access RDS
resource "aws_security_group_rule" "django_to_rds" {
  type                     = "ingress"
  from_port                = 5432
  to_port                  = 5432
  protocol                 = "tcp"
  source_security_group_id = module.ec2_django.django_sg_id
  security_group_id        = module.rds.rds_sg_id

  description = "Allow Django EC2 to connect to RDS PostgreSQL"
}

# Allow Celery SG to access RDS
resource "aws_security_group_rule" "celery_to_rds" {
  type                     = "ingress"
  from_port                = 5432
  to_port                  = 5432
  protocol                 = "tcp"
  source_security_group_id = module.ec2_celery.celery_sg_id
  security_group_id        = module.rds.rds_sg_id

  description = "Allow Celery EC2 to connect to RDS PostgreSQL"
}

# EC2 Celery Workers
module "ec2_celery" {
  source = "./modules/ec2_celery"

  vpc_id               = module.network.vpc_id
  public_subnets       = module.network.public_subnets
  ami_id               = local.ami_id
  key_name             = local.key_name
  github_token         = var.github_token
  env_file             = local.generated_env_file
  iam_instance_profile = "LabInstanceProfile"

  tags = local.common_tags

  depends_on = [module.rds, module.sqs]
}

# ─────────────────────────────────────────────────────
# EC2 DynamoDB Local (for FastAPI data storage)
# ─────────────────────────────────────────────────────
module "ec2_dynamodb" {
  source = "./modules/ec2_dynamodb"

  vpc_id          = module.network.vpc_id
  public_subnets = module.network.public_subnets
  ami_id          = local.ami_id
  key_name        = local.key_name
  env_file        = local.generated_env_file
  iam_instance_profile = "LabInstanceProfile"

  tags = local.common_tags
}

# ─────────────────────────────────────────────────────
# Dynamic .env for FastAPI (with DynamoDB endpoint)
# ─────────────────────────────────────────────────────
locals {
  dynamodb_endpoint = "http://${module.ec2_dynamodb.private_ip}:8000"
  
  generated_env_file_fastapi = <<-EOT
# FastAPI Environment Variables
DYNAMODB_ENDPOINT=${local.dynamodb_endpoint}
AWS_REGION=us-east-1
AWS_CLOUDWATCH_LOG_GROUP=/arquisoft/fastapi
AWS_CLOUDWATCH_RETENTION_DAYS=90
FASTAPI_DEBUG=False
  EOT
}

# ─────────────────────────────────────────────────────
# EC2 FastAPI (uses dynamic .env with DynamoDB endpoint)
# ─────────────────────────────────────────────────────
module "ec2_fastapi" {
  source = "./modules/ec2_fastapi"

  vpc_id               = module.network.vpc_id
  public_subnets       = module.network.public_subnets
  ami_id               = local.ami_id
  key_name             = local.key_name
  github_token         = var.github_token
  env_file             = local.generated_env_file_fastapi
  target_group_arn     = module.alb.fastapi_target_group_arn
  alb_sg_id            = module.alb.alb_sg_id
  iam_instance_profile = "LabInstanceProfile"

  tags = local.common_tags

  depends_on = [module.ec2_dynamodb]
}

# ─────────────────────────────────────────────────────
# Security Group Rules - FastAPI <-> DynamoDB
# ─────────────────────────────────────────────────────
resource "aws_security_group_rule" "fastapi_to_dynamodb" {
  type                     = "ingress"
  from_port                = 8000
  to_port                  = 8000
  protocol                 = "tcp"
  source_security_group_id = module.ec2_fastapi.fastapi_sg_id
  security_group_id        = module.ec2_dynamodb.dynamodb_sg_id

  description = "Allow FastAPI to connect to DynamoDB Local"
}

# EC2 Frontend (Nginx + React)
module "ec2_frontend" {
  source = "./modules/ec2_frontend"

  vpc_id              = module.network.vpc_id
  public_subnets      = module.network.public_subnets
  ami_id              = local.ami_id
  key_name            = local.key_name
  github_token        = var.github_token
  django_alb_dns      = module.alb.alb_dns_name
  tls_certificate_pem = module.tls_certificate.certificate_pem
  tls_private_key_pem = module.tls_certificate.private_key_pem

  tags = local.common_tags
}

# ─────────────────────────────────────────────────────
# CloudWatch Logs (ASR-10 — Audit Logs 90 days)
# ─────────────────────────────────────────────────────
module "cloudwatch" {
  source = "./modules/cloudwatch"

  log_group_prefix = "/arquisoft"
  retention_days   = 90

  tags = local.common_tags
}

# ─────────────────────────────────────────────────────
# AWS SES (Simple Email Service)
# ─────────────────────────────────────────────────────
module "ses" {
  source = "./modules/ses"

  sender_email          = "noreply@arquisoft.com"
  recipient_email       = var.recipient_email
  success_template_name = "analisis-resultado-exito"
  failure_template_name = "analisis-resultado-error"

  tags = local.common_tags
}
